shop/api1/urls.py
from django.urls import path
from . import views

app_name = 'api1'
urlpatterns = [
    path('products/', views.products, name='products'),
    path('products/<int:pk>/', views.product_details, name='product_details'),
]


"""
Получить список товаров
GET http://127.0.0.1/api/v1/product/

Создать товар
POST http://127.0.0.1/api/v1/product/     - данные form/json (наименование, цена и.д.)



Получить один товар
GET http://127.0.0.1/api/v1/product/5     - пример запроса

Обновить товар
POST  http://127.0.0.1/api/v1/product/5    - данные form/json (наименование, цена и.д.)
PUT   http://127.0.0.1/api/v1/product/5    - данные form/json (наименование, цена, гарантия) - обновить все

PATCH http://127.0.0.1/api/v1/product/5/name
PATCH http://127.0.0.1/api/v1/product_name/5/ - WRONG!
PATCH http://127.0.0.1/api/v1/product/5/photo_url    - данные form/json (наименование, цена) - обновить не все


Удалить товар
DELETE  http://127.0.0.1/api/v1/product/5
"""

shop/cart/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('<int:pk>/', login_required(views.CartView.as_view()), name='index'),
    path('item/add/<int:goods_id>/', views.cart_item_add, name='cartItemAdd'),
    path('<int:cartId>/item/inc/<int:goodsId>/', views.cart_item_inc, name='cartItemInc'),
    path('<int:cartId>/item/dec/<int:goodsId>/', views.cart_item_dec, name='cartItemDec'),
    # path('<slug:slug>/', views.GoodsPropsView.as_view(), name='props'),
]

shop/contacts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required, permission_required


app_name = 'contacts'
urlpatterns = [
    path('',                views.IndexView.as_view(),  name='index'),
    # path('', login_required(views.IndexView.as_view()), name='index'),
]

shop/goods/urls.py
from django.urls import path
from . import views

app_name = 'goods'
urlpatterns = [
    path('', views.GoodsView.as_view(), name='index'),
    path('<int:pk>/', views.GoodsPropsView.as_view(), name='details'),
    # path('<slug:slug>/', views.GoodsPropsView.as_view(), name='props'),
]

shop/internetshop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


"""
"""

urlpatterns = [
    path('api/v1/', include('api1.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile', include('userprofile.urls')),
    path('admin/', admin.site.urls),
    path('contacts/', include('contacts.urls')),
    path('goods/', include('goods.urls')),
    path('cart/', include('cart.urls')),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/contacts/models.py
from django.db import models


class Contacts(models.Model):
    page = models.TextField

shop/contacts/views.py
from django.views import generic
from .models import Contacts


class IndexView(generic.ListView):
    template_name = 'contacts.html'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Contacts.objects.all()

shop/templates/login.html
{% extends "base/base.html" %}
{% load static %}


{% block content %}
    <!-- slider Area Start-->
    <div class="slider-area ">
        <!-- Mobile Menu -->
        <div class="single-slider slider-height2 d-flex align-items-center" data-background="assets/img/hero/category.jpg">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center">
                            <h2>Login</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider Area End-->

    <!--================login_part Area =================-->
    <section class="login_part section_padding ">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6">
                    <div class="login_part_text text-center">
                        <div class="login_part_text_iner">
                            <h2>New to our Shop?</h2>
                            <p>There are advances being made in science and technology
                                everyday, and a good example of this is the</p>
                            <a href="#" class="btn_3">Create an Account</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="login_part_form">
                        <div class="login_part_form_iner">
                            <h3>Welcome Back ! <br>
                                Please Sign in now</h3>
                            <form class="row contact_form" action="#" method="post" novalidate="novalidate">
                                <div class="col-md-12 form-group p_star">
                                    <input type="text" class="form-control" id="name" name="name" value=""
                                        placeholder="Username">
                                </div>
                                <div class="col-md-12 form-group p_star">
                                    <input type="password" class="form-control" id="password" name="password" value=""
                                        placeholder="Password">
                                </div>
                                <div class="col-md-12 form-group">
                                    <div class="creat_account d-flex align-items-center">
                                        <input type="checkbox" id="f-option" name="selector">
                                        <label for="f-option">Remember me</label>
                                    </div>
                                    <button type="submit" value="submit" class="btn_3">
                                        log in
                                    </button>
                                    <a class="lost_pass" href="#">forget password?</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================login_part end =================-->
{% endblock %}

shop/templates/product_list.html
{% extends "base/base.html" %}
{% load static %}


{% block content %}
    <!-- slider Area Start-->
    <div class="slider-area ">
        <!-- Mobile Menu -->
        <div class="single-slider slider-height2 d-flex align-items-center" data-background="assets/img/hero/category.jpg">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center">
                            <h2>product list</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider Area End-->
    
    <!-- product list part start-->
    <section class="product_list section_padding">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="product_sidebar">
                        <div class="single_sedebar">
                            <form action="#">
                                <input type="text" name="#" placeholder="Search keyword">
                                <i class="ti-search"></i>
                            </form>
                        </div>
                        <div class="single_sedebar">
                            <div class="select_option">
                                <div class="select_option_list">Category <i class="right fas fa-caret-down"></i> </div>
                                <div class="select_option_dropdown">
                                    <p><a href="#">Category 1</a></p>
                                    <p><a href="#">Category 2</a></p>
                                    <p><a href="#">Category 3</a></p>
                                    <p><a href="#">Category 4</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="single_sedebar">
                            <div class="select_option">
                                <div class="select_option_list">Type <i class="right fas fa-caret-down"></i> </div>
                                <div class="select_option_dropdown">
                                    <p><a href="#">Type 1</a></p>
                                    <p><a href="#">Type 2</a></p>
                                    <p><a href="#">Type 3</a></p>
                                    <p><a href="#">Type 4</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="product_list">
                        <div class="row">
                            {% for goods in goods_list %}
                            <div class="col-lg-6 col-sm-6">
                                <div class="single_product_item">
                                    <img src="{{ goods.productId.image.url }}" alt="" class="img-fluid">
                                    <h3> <a href="{% url 'goods:details' goods.id %}">{{ goods.productId.name }}</a> </h3>
                                    <p>{{ goods.price }}</p>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="load_more_btn text-center">
                            <a href="#" class="btn_3">Load More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- product list part end-->
    
    <!-- client review part here -->
    <section class="client_review">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="client_review_slider owl-carousel">
                        <div class="single_client_review">
                            <div class="client_img">
                                <img src="assets/img/client.png" alt="#">
                            </div>
                            <p>"Working in conjunction with humanitarian aid agencies, we have supported programmes to help alleviate human suffering.</p>
                            <h5>- Micky Mouse</h5>
                        </div>
                        <div class="single_client_review">
                            <div class="client_img">
                                <img src="assets/img/client_1.png" alt="#">
                            </div>
                            <p>"Working in conjunction with humanitarian aid agencies, we have supported programmes to help alleviate human suffering.</p>
                            <h5>- Micky Mouse</h5>
                        </div>
                        <div class="single_client_review">
                            <div class="client_img">
                                <img src="assets/img/client_2.png" alt="#">
                            </div>
                            <p>"Working in conjunction with humanitarian aid agencies, we have supported programmes to help alleviate human suffering.</p>
                            <h5>- Micky Mouse</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- client review part end -->

    <!-- Shop Method Start-->
    <div class="shop-method-area section-padding30">
        <div class="container">
            <div class="row d-flex justify-content-between">
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <div class="single-method mb-40">
                        <i class="ti-package"></i>
                        <h6>Free Shipping Method</h6>
                        <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <div class="single-method mb-40">
                        <i class="ti-unlock"></i>
                        <h6>Secure Payment System</h6>
                        <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                    </div>
                </div> 
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <div class="single-method mb-40">
                        <i class="ti-reload"></i>
                        <h6>Secure Payment System</h6>
                        <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Shop Method End-->

    <!-- subscribe part here -->
    <section class="subscribe_part section_padding">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="subscribe_part_content">
                        <h2>Get promotions & updates!</h2>
                        <p>Seamlessly empower fully researched growth strategies and interoperable internal or “organic” sources credibly innovate granular internal .</p>
                        <div class="subscribe_form">
                            <input type="email" placeholder="Enter your mail">
                            <a href="#" class="btn_1">Subscribe</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- subscribe part end -->
{% endblock %}

shop/templates/single-product.html
{% extends "base/base.html" %}
{% load static %}


{% block content %}
<!-- slider Area Start-->
<div class="slider-area ">
    <!-- Mobile Menu -->
    <div class="single-slider slider-height2 d-flex align-items-center" data-background="assets/img/hero/category.jpg">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>product Details</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- slider Area End-->

<!--================Single Product Area =================-->
<div class="product_image_area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="product_img_slide owl-carousel">
                    <div class="single_product_img">
                        <img src="{{ goods.productId.photo_url }}" alt="#" class="img-fluid">
                    </div>
                    <!--            <div class="single_product_img">-->
                    <!--              <img src="assets/img/product/single_product.png" alt="#" class="img-fluid">-->
                    <!--            </div>-->
                    <!--            <div class="single_product_img">-->
                    <!--              <img src="assets/img/product/single_product.png" alt="#" class="img-fluid">-->
                    <!--            </div>-->
                </div>
            </div>
            <div class="col-lg-8">
                <div class="single_product_text text-center">
                    <h3>{{ goods.productId.name }}</h3>
                    <p>
                        {{ goods.productId.description }}
                    </p>
                    <p>
                        {{ goods.price }}
                    </p>
                    <div class="card_area">
                        <div class="product_count_area">
                            <p>Quantity</p>
                            <div class="product_count d-inline-block">
                                <span class="product_count_item inumber-decrement"> <i class="ti-minus"></i></span>
                                <input class="product_count_item input-number" type="text" value="1" min="0" max="10">
                                <span class="product_count_item number-increment"> <i class="ti-plus"></i></span>
                            </div>
                            <p>$5</p>
                        </div>
                        <div class="add_to_cart">
                            <script type="application/javascript">
                                var csrfcookie = function() {
                                    var cookieValue = null,
                                        name = 'csrftoken';
                                    if (document.cookie && document.cookie !== '') {
                                        var cookies = document.cookie.split(';');
                                        for (var i = 0; i < cookies.length; i++) {
                                            var cookie = cookies[i].trim();
                                            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                                break;
                                            }
                                        }
                                    }
                                    console.log("cookieValue", cookieValue);
                                    return cookieValue;
                                };

                                function cartItemInc() {
                                    // Form fields, see IDs above
                                    const http = new XMLHttpRequest()
                                    http.open('GET', "{% url 'cart:cartItemAdd' goods.id %}")
                                    // http.open('POST', "{% url 'cart:cartItemAdd' goods.id %}")
                                    http.setRequestHeader('Content-type', 'application/json')
                                    // http.setRequestHeader('X-CSRFToken', csrfcookie());
                                    http.send(JSON.stringify({})) // Make sure to stringify
                                    http.onload = function() {
                                        // Do whatever with response
                                    }
                                }
                            </script>
                            <a href="#" class="btn_3" onclick="cartItemInc();">add to cart</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--================End Single Product Area =================-->
<!-- subscribe part here -->
<!--   <section class="subscribe_part section_padding">-->
<!--      <div class="container">-->
<!--          <div class="row justify-content-center">-->
<!--              <div class="col-lg-8">-->
<!--                  <div class="subscribe_part_content">-->
<!--                      <h2>Get promotions & updates!</h2>-->
<!--                      <p>Seamlessly empower fully researched growth strategies and interoperable internal or “organic” sources credibly innovate granular internal .</p>-->
<!--                      <div class="subscribe_form">-->
<!--                          <input type="email" placeholder="Enter your mail">-->
<!--                          <a href="#" class="btn_1">Subscribe</a>-->
<!--                      </div>-->
<!--                  </div>-->
<!--              </div>-->
<!--          </div>-->
<!--      </div>-->
<!--  </section>-->
<!-- subscribe part end -->
{% endblock %}