shop/api1/urls.py
from django.urls import path
from . import views

app_name = 'api1'
urlpatterns = [
    path('products/', views.products, name='products'),
    path('products/<int:pk>/', views.product_details, name='product_details'),
]


"""
Получить список товаров
GET http://127.0.0.1/api/v1/product/

Создать товар
POST http://127.0.0.1/api/v1/product/     - данные form/json (наименование, цена и.д.)



Получить один товар
GET http://127.0.0.1/api/v1/product/5     - пример запроса

Обновить товар
POST  http://127.0.0.1/api/v1/product/5    - данные form/json (наименование, цена и.д.)
PUT   http://127.0.0.1/api/v1/product/5    - данные form/json (наименование, цена, гарантия) - обновить все

PATCH http://127.0.0.1/api/v1/product/5/name
PATCH http://127.0.0.1/api/v1/product_name/5/ - WRONG!
PATCH http://127.0.0.1/api/v1/product/5/photo_url    - данные form/json (наименование, цена) - обновить не все


Удалить товар
DELETE  http://127.0.0.1/api/v1/product/5
"""

shop/contacts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required, permission_required


app_name = 'contacts'
urlpatterns = [
    path('',                views.IndexView.as_view(),  name='index'),
    # path('', login_required(views.IndexView.as_view()), name='index'),
]

shop/goods/urls.py
from django.urls import path
from . import views

app_name = 'goods'
urlpatterns = [
    path('', views.GoodsView.as_view(), name='index'),
    path('<int:pk>/', views.GoodsPropsView.as_view(), name='details'),
    # path('<slug:slug>/', views.GoodsPropsView.as_view(), name='props'),
]

shop/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    # path('/', views.IndexView.as_view(), name='index'),
    path('', views.index, name='index'),
    path('api/', views.api, name='api'),
]

shop/internetshop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


"""
"""

urlpatterns = [
    path('api/v1/', include('api1.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile', include('userprofile.urls')),
    path('admin/', admin.site.urls),
    path('contacts/', include('contacts.urls')),
    path('goods/', include('goods.urls')),
    path('cart/', include('cart.urls')),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/userprofile/urls.py
from django.urls import path
from . import views
# from django.contrib.auth.decorators import login_required

app_name = 'userprofile'
urlpatterns = [
    path('', views.ProfileView.as_view(), name='index'),
    # path('', login_required(views.ProfileView.as_view()), name='index'),
    # path('', views.index, name='index'),
]

shop/templates/base/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}eCommerce HTML-5 Template{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

{% block preloader-active %}
<!-- Preloader Start -->
<div id="preloader-active">
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="preloader-inner position-relative">
            <div class="preloader-circle"></div>
            <div class="preloader-img pere-text">
                <img src="{% static 'img/logo/logo.png' %}" alt="">
            </div>
        </div>
    </div>
</div>
<!-- Preloader Start -->
{% endblock %}

{% block header %}
    {% include "base/header.html" %}
{% endblock %}

{% block content %}{% endblock %}

{% block footer %}
    {% include "base/footer.html" %}
{% endblock %}

{%  include "base/scripts.html" %}

</body>
</html>

shop/templates/base/footer.html
{% load static %}
<footer>

    <!-- Footer Start-->
    <div class="footer-area footer-padding">
        <div class="container">
            <div class="row d-flex justify-content-between">
                <div class="col-xl-3 col-lg-3 col-md-5 col-sm-6">
                    <div class="single-footer-caption mb-50">
                        <div class="single-footer-caption mb-30">
                            <!-- logo -->
                            <div class="footer-logo">
                                <a href="{% url 'home:index' %}"><img src="{% static 'img/logo/logo2_footer.png' %}" alt=""></a>
                            </div>
                            <div class="footer-tittle">
                                <div class="footer-pera">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmod tempor
                                        incididunt ut labore.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 col-lg-3 col-md-3 col-sm-5">
                    <div class="single-footer-caption mb-50">
                        <div class="footer-tittle">
                            <h4>Quick Links</h4>
                            <ul>
                                <li><a href="#">About</a></li>
                                <li><a href="#"> Offers & Discounts</a></li>
                                <li><a href="#"> Get Coupon</a></li>
                                <li><a href="#"> Contact Us</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-7">
                    <div class="single-footer-caption mb-50">
                        <div class="footer-tittle">
                            <h4>New Products</h4>
                            <ul>
                                <li><a href="#">Woman Cloth</a></li>
                                <li><a href="#">Fashion Accessories</a></li>
                                <li><a href="#"> Man Accessories</a></li>
                                <li><a href="#"> Rubber made Toys</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-5 col-sm-7">
                    <div class="single-footer-caption mb-50">
                        <div class="footer-tittle">
                            <h4>Support</h4>
                            <ul>
                                <li><a href="#">Frequently Asked Questions</a></li>
                                <li><a href="#">Terms & Conditions</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Report a Payment Issue</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer bottom -->
            <div class="row">
                <div class="col-xl-7 col-lg-7 col-md-7">
                    <div class="footer-copy-right">
                        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                            All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i>
                            by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
                <div class="col-xl-5 col-lg-5 col-md-5">
                    <div class="footer-copy-right f-right">
                        <!-- social -->
                        <div class="footer-social">
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                            <a href="#"><i class="fab fa-behance"></i></a>
                            <a href="#"><i class="fas fa-globe"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End-->

</footer>

shop/templates/base/header.html
{% load static %}
<header>
    <!-- Header Start -->
    <div class="header-area">
        <div class="main-header ">
            <div class="header-top top-bg d-none d-lg-block">
                <div class="container-fluid">
                    <div class="col-xl-12">
                        <div class="row d-flex justify-content-between align-items-center">
                            <div class="header-info-left d-flex">
                                <div class="flag">
                                    <img src="{% static 'img/icon/header_icon.png' %}" alt="">
                                </div>
                                <div class="select-this">
                                    <form action="#">
                                        <div class="select-itms">
                                            <select name="select" id="select1">
                                                <option value="">USA</option>
                                                <option value="">SPN</option>
                                                <option value="">CDA</option>
                                                <option value="">USD</option>
                                            </select>
                                        </div>
                                    </form>
                                </div>
                                <ul class="contact-now">
                                    <li>+777 2345 7886</li>
                                </ul>
                            </div>
                            <div class="header-info-right">
                                <ul>
                                    {% if user.is_staff %}
                                        <li><a href="/admin/" target="_blank">My Account </a></li>
                                    {% else %}
                                        <li><a href="{% url 'userprofile:index' %}" target="_blank">My Account </a></li>
                                        <!--                                        <li><a href="my_account.html">My Account </a></li> -->
                                    {% endif %}
                                    <li><a href="product_list.html">Wish List </a></li>
                                    <li><a href="cart.html">Shopping</a></li>
                                    <li><a href="cart.html">Cart</a></li>
                                    {% if user.is_authenticated %}
                                        <li><a href="{% url 'logout' %}?next={{ request.path }}">Checkout</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header-bottom  header-sticky">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <!-- Logo -->
                        <div class="col-xl-1 col-lg-1 col-md-1 col-sm-3">
                            <div class="logo">
                                <a href="{% static 'base.html/' %}"><img src="{% static 'img/logo/logo.png' %}" alt=""></a>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-8 col-md-7 col-sm-5">
                            <!-- Main-menu -->
                            <div class="main-menu f-right d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a href="{% url 'home:index' %}">Home</a></li>
                                        <li><a href="{% url 'goods:index' %}">Goods</a></li>
                                        <li><a href="blog.html">Blog</a>
                                            <ul class="submenu">
                                                <li><a href="blog.html">Blog</a></li>
                                                <li><a href="single-blog.html">Blog Details</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="#">Pages</a>
                                            <ul class="submenu">
                                                {% if user.is_authenticated == False %}
                                                    <li><a href="{% url 'login' %}">Login</a></li>
                                                {% endif %}
                                                <li><a href="cart.html">Card</a></li>
                                                <li><a href="elements.html">Element</a></li>
                                                <li><a href="about.html">About</a></li>
                                                <li><a href="confirmation.html">Confirmation</a></li>
                                                <li><a href="cart.html">Shopping Cart</a></li>
                                                {% if user.is_authenticated %}
                                                    <li><a href="{% url 'logout' %}">Checkout</a></li>
                                                {% endif %}
                                            </ul>
                                        </li>
                                        <li><a href="{% url 'contacts:index' %}">Contact</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-5 col-lg-3 col-md-3 col-sm-3 fix-card">
                            <ul class="header-right f-right d-none d-lg-block d-flex justify-content-between">
                                <li class="d-none d-xl-block">
                                    <div class="form-box f-right ">
                                        <input type="text" name="Search" placeholder="Search products">
                                        <div class="search-icon">
                                            <i class="fas fa-search special-tag"></i>
                                        </div>
                                    </div>
                                </li>
                                <li class=" d-none d-xl-block">
                                    <div class="favorit-items">
                                        <i class="far fa-heart"></i>
                                    </div>
                                </li>
                                <li>
                                    <div class="shopping-card">
                                        <a href="cart.html"><i class="fas fa-shopping-cart"></i></a>
                                    </div>
                                </li>
                                {% if not user.is_authenticated %}
                                    <li class="d-none d-lg-block"><a href="{% url 'django_registration_register' %}" class="btn header-btn">Sign in</a></li>
                                {% endif %}
                            </ul>
                        </div>
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
</header>

shop/templates/base/scripts.html
{% load static %}
<!-- JS here -->

<!-- All JS Custom Plugins Link Here here -->
<script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
<!-- Jquery, Popper, Bootstrap -->
<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Jquery Mobile Menu -->
<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>

<!-- Jquery Slick , Owl-Carousel Plugins -->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>

<!-- One Page, Animated-HeadLin -->
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/animated.headline.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.js' %}"></script>

<!-- Scrollup, nice-select, sticky -->
<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>

<!-- contact js -->
<script src="{% static 'js/contact.js' %}"></script>
<script src="{% static 'js/jquery.form.js' %}"></script>
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/mail-script.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>

<!-- Jquery Plugins, main Jquery -->
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>